### ISSUE TITLE
HTML Quiz Bug

### ISSUE THREAD

**Issue by LuanEdCosta** [Ebazhanov/linkedin-skill-assessments-quizzes#1086]
The HTML quiz is showing weird elements on the page.
I believe that there is a typo in the question 20 because is where the errors begin to show.

![image](https://user-images.githubusercontent.com/36794274/107101372-d732a100-67f5-11eb-8ad0-e832269e8269.png)

**Comment by rradfar** [comment]
@LuanEdCosta Thanks Luan! What device, link, and browser are you using to view the HTML quiz? I am trying to see if I can reproduce this bug.

**Comment by LuanEdCosta** [comment]
I'm using Google Chrome v88.0 on a Windows 10 computer and accessing the website hosted on GitHub Pages to see the quiz.
[link to the quiz](https://ebazhanov.github.io/linkedin-skill-assessments-quizzes/html/html-quiz.html)

I'm new in this repository but i will try to help. 😄👍

**Comment by rradfar** [comment]
@LuanEdCosta Awesome, thanks! I will see if I can find out what's causing it.

And welcome to the repo! Extra help & contribution is always appreciated! 😄

**Comment by rradfar** [comment]
So it appears that on that github.io page, html is being parsed instead of just being displayed in raw format even though it is wrapped in an html code block. so for example this code block 

```html
<details>
  <summary>Parmesan Deviled Eggs</summary>
  <p>
    These delectable little bites are made with organic eggs, fresh Parmesan, and chopped pine nuts.
  </p>
</details>
```

is being parsed into an actual drop down like [this](https://imgur.com/Py2lsZJ). As you can see from this example, this bug doesn't happen here on GitHub but it does happen on GitHub pages (github.io).

I'm not too familiar with the intricacies of hosting on GitHub pages so I will defer to @Ebazhanov on this one! He is the wise one!

**Comment by Ebazhanov** [comment]
Thank you, @LuanEdCosta, for finding the bug and raising this issue! :clap: :pray:
@rradfar good discussion! 
The fix is pretty simple I just replay `html` into `markdown` looks like `jekyll github pages` not working correctly with this.
https://ebazhanov.github.io/linkedin-skill-assessments-quizzes/html/html-quiz.html
In general great job guys :fire:! Have a good weekend for all of us!:beer:

**Comment by rradfar** [comment]
@Ebazhanov Very cool! I guess the downside to this is that we lose the syntax highlighting for HTML tags but I don't think that's a big deal.

I noticed that you have added back the blank lines after each question. Is this the approach that you would like us to take for all the quizes? Because that's something I used to do but I noticed that in one of the [latest commits](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/commit/981c12c614dcbc427871cb86f4a39e58eb70c704#diff-9229918d7e1d7670ca457b9ebc211226d99db0166798fea6fea9c6cbc6b84c88) we got rid of all blank lines after questions. So I adjusted my Linter accordingly to not warn me about not having blank lines after headings. Which one do you prefer? Blank lines after headings (questions) or no blank lines?
