### ISSUE TITLE
CSS - Questions changed

### ISSUE THREAD

**Issue by devhyunjae** [Ebazhanov/linkedin-skill-assessments-quizzes#1167]
<img width="960" alt="Screen Shot 2021-02-16 at 2 22 01 PM" src="https://user-images.githubusercontent.com/12890257/108294119-96189480-71d8-11eb-8cb4-659d9c0a02ca.png">
<img width="994" alt="Screen Shot 2021-02-16 at 2 19 08 PM" src="https://user-images.githubusercontent.com/12890257/108294124-987aee80-71d8-11eb-9f8e-fb7b58ff2107.png">
<img width="1049" alt="Screen Shot 2021-02-16 at 2 17 32 PM" src="https://user-images.githubusercontent.com/12890257/108294129-99ac1b80-71d8-11eb-8120-ebe75d7406bb.png">

Options and answer is same. Only question sentence changed.

Want me to make a new pr for this?

**Comment by rradfar** [comment]
@devhyunjae Thanks Hyunjae! Because the wording is so similar, instead of creating new questions, I suggest adding the alternative versions to the current ones. So for instance, based on your first slide,

#### Q6. What is true of block and inline elements?
```
#### Q6. What is true of block and inline elements?
```
can be written as 
#### Q6. What is true of block and inline elements? (_Alternative_: Which statement about block and inline elements is true?)
```
#### Q6. What is true of block and inline elements? (_Alternative_: Which statement about block and inline elements is true?)
```

That is just my suggestion. I would wait to see if @Ebazhanov is okay with this or wants to take a different approach.

**Comment by Ebazhanov** [comment]
Yes sure @rradfar, very good idea!
Thank you, @devhyunjae, for raising this issue, we would be happy to merge your PR as soon as we get it! Have a good evening!
