### ISSUE TITLE
C++ question 37 is wrong

### ISSUE THREAD

**Issue by yangjiel** [Ebazhanov/linkedin-skill-assessments-quizzes#2143]
By running the code, Q37 should be B not A.

**Comment by CS4Usama** [comment]
> By running the code, Q37 should be B not A.

No @yangjiel brother, for C++ Q37 correct answer will be A. Because the B option gives the same output as in the question mentioned, we have to find those statement who doesn't produce the same output as compare to the statement's code snippet output.

- **Statement Code Snippet**
```
for (i=1;i<10;i++) {
    cout<<i<<endl;
}
```
_Output:   1 2 3 4 5 6 7 8 9_
<br>

- **Option A Code Snippet**
```
i=1;
while(i<10) {
    cout<<++i<<endl;
}
```
_Output:   2 3 4 5 6 7 8 9 10_   &nbsp; &nbsp; &nbsp; (different from Statement Code Snippet Output)
<br>

- **Option B Code Snippet**
```
for (int i:{1,2,3,4,5,6,7,8,9}) {
    cout<<i<<endl;
}
```
_Output:   1 2 3 4 5 6 7 8 9_   &nbsp; &nbsp; &nbsp; (same as Statement Code Snippet Output)
<br>
So, Option A does not produce the same output as statement code snippet. And this is the correct answer.

**Comment by yangjiel** [comment]
My bad. I thought the question is asking which is generating the same output.
