### ISSUE TITLE
JavaScript - New Assessment Questions

### ISSUE THREAD

**Issue by ethanosullivan** [Ebazhanov/linkedin-skill-assessments-quizzes#2856]
Here are some new questions that I discovered when taking the [JavaScript assessment](https://ebazhanov.github.io/linkedin-skill-assessments-quizzes/javascript/javascript-quiz.html). I wasn't confident in my answers, so maybe someone else can chime-in.

```markdown
### Q1. Which statement prints "roar" to the console?
var sound  "grunt";
var bear = { sound: "roar"}; 
function roar){
  console.log(this.sound);

- [ ] bear.bind(roar);
- [ ] roar.bind(bear);
- [ ] roar.apply(bear);
- [ ] bear[roar]();

### Q2. Which line could you add to this code to print "jaguar" to the console?
let animals = ["jaguar","eagle"];
//Missing Line
console.log(animals.pop()); //Prints jaguar

- [ ] `animals.filter(e => e === "jaguar");`
- [ ] `animals.reverse();`
- [ ] `animals.shift();`
- [x] `animals.pop();`

### Q3. Which snippet could you add to this code to print "food" to the console?
class Animal {
  static belly = [];
 eat () { Animal.belly.push("food"); }
let a = new Animal();
a.eat();
console.log(/* Snippet Here */); //Prints food
 
- [ ] `a.prototype.belly[0]`
- [ ] `Object.getPrototype0f (a).belly[0]`
- [ ] `Animal.belly[0]`
- [ ] `a.belly[0]`

**Comment by BHARGAVPATEL1244** [comment]
Q.2 answer = animals.pop();

**Comment by ethanosullivan** [comment]
Updated the original ticket with the correct answer for #2. I'll leave this open until the other two are solved.

**Comment by GalexyN** [comment]
@ethanosullivan 

Q1 is 3 roar.apply(bear)

ref [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply](url),  [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this](url)
, and [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind](url)
From my understanding, when this is called inside the function it gets assigned at run time, and references 'this' inside the scope of the function. So if you ran ```roar()``` you'd get undefined since there is no sound variable inside the scope of the roar function. Since the ultimate goal is console.log 'roar' you'd need to apply the bear object when calling roar so 'this' takes the scope of the bear object and now has a 'this.sound'.

- [ ] bear.bind(roar); // you can't call bind on an object its a function method
- [ ] roar.bind(bear); // bind will bind the correct this value but it doesn't call the function so you would need to change this to ```roar.bind(bear)()``` for it to work properly
- [X] roar.apply(bear); // this is our ultimate answer since it will bind and also all the function after
- [ ] bear[roar](); // bear doesn't have a roar key


I believe @BHARGAVPATEL1244 's answer is correct animals.reverse() will reverse the entire array so when it calls ```console.log(animals.pop())``` which removes and returns the last element in the array 'jaguar' will now be at the end

ref [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse](url)

Q3 is the third option as well. 'Animal.belly[0]'

When Animal is instantiated the static keyword essentially tells us that belly is only accessible when calling directly from the class itself vs instances of the class 

ref [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static](url)

**Comment by GalexyN** [comment]
I can take this issue as well @Ebazhanov

**Comment by GalexyN** [comment]
This is finished @Ebazhanov 

Is there a syntax issue with my PR? #2872 I thought it would auto close referenced issues if merged.

**Comment by Ebazhanov** [comment]
agree with you @GalexyN it should be closed with sync to your PR, hmm very strange.
anyway thank you for great contribution 💪 
and thank you @ethanosullivan for creating this issue 🌷
