### ISSUE TITLE
Python - New Assessment Questions

### ISSUE THREAD

**Issue by ethanosullivan** [Ebazhanov/linkedin-skill-assessments-quizzes#2857]
Here are some new questions that I discovered when taking the [Python assessment](https://ebazhanov.github.io/linkedin-skill-assessments-quizzes/python/python-quiz.html). I wasn't confident in my answers, so maybe someone else can chime-in.

```markdown
### Q1. What is the output of this code? (NumPy has been imported as np.)
table = np.array([
    [1,3],
    [2,4]])
print(table.max(axis=1))

- [ ] `[2, 4]`
- [ ] `[3, 4]`
- [ ] `[4]`
- [ ] `[1,2]`

### Q2. What will this code print?
number = 3
print (f"The number is {number}")

- [ ] `The number is 3`
- [ ] `the number is 3`
- [ ] `THE NUMBER IS 3`
- [ ] It throws a TypeError because the integer must be cast to a string.

### Q3. Which syntax correctly creates a variable that is bound to a tuple?
- [ ] `my_tuple tup(2, 'apple', 3.5) %D`
- [ ] `my_tuple [2, 'apple', 3.5].tuple() %D`
- [ ] `my_tuple = (2, 'apple', 3.5)`
- [ ] `my_tuple = [2, 'apple', 3.5]`
```

**Comment by BHARGAVPATEL1244** [comment]
#2860 added your question with reference

**Comment by ethanosullivan** [comment]
Looks great, thanks. Closing ticket.

**Comment by sakshi-2singh** [comment]
### Q1. What is the output of this code? (NumPy has been imported as np.)
table = np.array([
    [1,3],
    [2,4]])
print(table.max(axis=1))

- [ ] `[2, 4]`
- [ ] `[3, 4]`
- [ ] `[4]`
- [ ] `[1,2]`

### Q2. What will this code print?
number = 3
print (f"The number is {number}")

- [ ] `The number is 3`
- [ ] `the number is 3`
- [ ] `THE NUMBER IS 3`
- [ ] It throws a TypeError because the integer must be cast to a string.

### Q3. Which syntax correctly creates a variable that is bound to a tuple?
- [ ] `my_tuple tup(2, 'apple', 3.5) %D`
- [ ] `my_tuple [2, 'apple', 3.5].tuple() %D`
- [ ] `my_tuple = (2, 'apple', 3.5)`
- [ ] `my_tuple = [2, 'apple', 3.5]`
