### ISSUE TITLE
Actualise numbers of questions & answers in Readme.md

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3533]
![image](https://user-images.githubusercontent.com/13170022/163686286-34397768-3067-4deb-86fd-a3c6746dac5c.png)

**Comment by gregglind** [comment]
Confirm Goal:  Is the Goal to keep these counts current and correct?

Solutions:
Are you thinking automated process would help, or is manual better?  
For automation, 
A/ (github history) to find 'potentially dirty' languages.
B/ 'grep' to find question and answer 'guesses'.

If manual:
C/ Someone goes through the recent changes, finds 'dirty' quizzes, and updates the count.

**Comment by Ebazhanov** [comment]
Thanks @gregglind for suggestion, but I do not have experience and not sure if someone want's to spend time to do such small updates which can take less then 30 min. So my answer it can be easy to do manually. But your idea sounds great!

**Comment by jdelucca** [comment]
Pasted from the Pull request https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4761:  Trying to automate counting the number of questions that are posted and how many of them are answered with a python script for this issue

To do this, I removed curly quotes from a bunch of different files, and a few other odd characters including a dog emoji :dog: in css-quiz, and changed the names of a few files/folders to be consistent with the others.

I did not write anything to automatically put the output of the counter into the main Readme.md file, and started doing it manually, before getting annoyed and giving up on it. 

Should be easier to automate now, if anyone wants to give it another shot, or just finish manually updating it.

**Comment by jdelucca** [comment]
The ones I didn't put in yet are (in filename, "total questions", "answered questions", "unanswered questions" format). It's not perfectly accurate, mostly because sometimes people will only post the answer, not bothering to write the incorrect answers down.

./c++/c++-quiz.md 85.0 [x] 84 [ ] 1.0
./c-(programming-language)/c-(programming-language)-quiz.md 78.0 [x] 78 [ ] 0.0
./c-sharp/c-sharp-quiz.md 72.0 [x] 72 [ ] 0.0
./css/css-quiz.md 154.25 [x] 155 [ ] -0.75
./cybersecurity/cybersecurity-quiz.md 117.75 [x] 121 [ ] -3.25
./django/django-quiz.md 76.0 [x] 76 [ ] 0.0
./dotnet-framework/dotnet-framework-quiz.md 71.25 [x] 72 [ ] -0.75
./eclipse/eclipse-quiz.md 43.0 [x] 36 [ ] 7.0
./front-end-development/front-end-development-quiz.md 85.0 [x] 85 [ ] 0.0
./git/git-quiz.md 133.0 [x] 133 [ ] 0.0
./go/go-quiz.md 45.0 [x] 45 [ ] 0.0
./google-ads/google-ads-quiz.md 50.0 [x] 50 [ ] 0.0
./google-analytics/google-analytics-quiz.md 86.0 [x] 85 [ ] 1.0
./google-cloud-platform/google-cloud-platform-quiz.md 58.0 [x] 58 [ ] 0.0
./hadoop/hadoop-quiz.md 68.75 [x] 61 [ ] 7.75
./html/html-quiz.md 110.5 [x] 111 [ ] -0.5
./it-operations/it-operations-quiz.md 69.0 [x] 69 [ ] 0.0
./java/java-quiz.md 147.0 [x] 147 [ ] 0.0
./javascript/javascript-quiz.md 141.0 [x] 142 [ ] -1.0
./jquery/jquery-quiz.md 81.0 [x] 79 [ ] 2.0
./json/json-quiz.md 87.25 [x] 87 [ ] 0.25
./kotlin/kotlin-quiz.md 88.0 [x] 89 [ ] -1.0
./linux/linux-quiz.md 94.25 [x] 93 [ ] 1.25
./logic-pro/logic-pro-quiz.md 17.0 [x] 17 [ ] 0.0
./machine-learning/machine-learning-quiz.md 102.75 [x] 103 [ ] -0.25
./matlab/matlab-quiz.md 70.0 [x] 71 [ ] -1.0
./maven/maven-quiz.md 68.0 [x] 65 [ ] 3.0
./microsoft-access/microsoft-access-quiz.md 30.0 [x] 30 [ ] 0.0
./microsoft-azure/microsoft-azure-quiz.md 55.0 [x] 55 [ ] 0.0
./microsoft-excel/microsoft-excel-quiz.md 144.0 [x] 145 [ ] -1.0
./microsoft-outlook/microsoft-outlook-quiz.md 93.25 [x] 72 [ ] 21.25
./microsoft-power-automate/microsoft-power-automate-quiz.md 26.25 [x] 24 [ ] 2.25
./microsoft-power-bi/microsoft-power-bi-quiz.md 85.0 [x] 84 [ ] 1.0
./microsoft-power-point/microsoft-power-point-quiz.md 99.0 [x] 99 [ ] 0.0
./microsoft-project/microsoft-project-quiz.md 45.0 [x] 44 [ ] 1.0
./microsoft-word/microsoft-word-quiz.md 95.0 [x] 95 [ ] 0.0
./mongodb/mongodb-quiz.md 84.0 [x] 86 [ ] -2.0
./mysql/mysql-quiz.md 113.0 [x] 113 [ ] 0.0
./node.js/node.js-quiz.md 75.0 [x] 75 [ ] 0.0
./nosql/nosql-quiz.md 48.0 [x] 47 [ ] 1.0
./object-oriented-programming/object-oriented-programming-quiz.md 95.5 [x] 96 [ ] -0.5
./objective-c/objective-c-quiz.md 41.0 [x] 39 [ ] 2.0
./php/php-quiz.md 97.5 [x] 101 [ ] -3.5
./pro-tools/pro-tools-quiz.md 2.0 [x] 2 [ ] 0.0
./python/python-quiz.md 157.75 [x] 159 [ ] -1.25
./quickbooks/quickbooks-quiz.md 46.0 [x] 39 [ ] 7.0
./r/r-quiz.md 54.75 [x] 54 [ ] 0.75
./reactjs/reactjs-quiz.md 105.0 [x] 105 [ ] 0.0
./rest-api/rest-api-quiz.md 68.0 [x] 68 [ ] 0.0
./revit/revit-quiz.md 14.0 [x] 14 [ ] 0.0
./ruby-on-rails/ruby-on-rails-quiz.md 75.75 [x] 71 [ ] 4.75
./rust/rust-quiz.md 42.0 [x] 42 [ ] 0.0
./scala/scala-quiz.md 50.0 [x] 47 [ ] 3.0
./search-engine-optimization/search-engine-optimization-quiz.md 76.0 [x] 75 [ ] 1.0
./sharepoint/sharepoint-quiz.md 40.0 [x] 37 [ ] 3.0
./sketchup/sketchup-quiz.md 2.0 [x] 2 [ ] 0.0
./solidworks/solidworks-quiz.md 57.0 [x] 57 [ ] 0.0
./spring-framework/spring-framework-quiz.md 84.75 [x] 75 [ ] 9.75
./swift/swift-quiz.md 69.25 [x] 70 [ ] -0.75
./t-sql/t-sql-quiz.md 50.25 [x] 50 [ ] 0.25
./unity/unity-quiz.md 52.0 [x] 50 [ ] 2.0
./vba/vba-quiz.md 58.5 [x] 48 [ ] 10.5
./visio/visio-quiz.md 41.0 [x] 41 [ ] 0.0
./windows-server/windows-server-quiz.md 71.0 [x] 74 [ ] -3.0
./wordpress/wordpress-quiz.md 80.0 [x] 79 [ ] 1.0
./xml/xml-quiz.md 47.0 [x] 46 [ ] 1.0

**Comment by AdityaShaw1** [comment]
pls assign me
