### ISSUE TITLE
OOP Question 65

### ISSUE THREAD

**Issue by FlorinChess** [Ebazhanov/linkedin-skill-assessments-quizzes#3849]
The question is incomplete and there are no answer options listed

**Comment by lucioaguiar** [comment]
Hello friend, I believe the answer to question 65 is letter **(c) "queuing outbound requests to action when connectivity has been lost"**. I believe that if the device is not connected or has lost the connection, it has no reason to mount a queue or make several attempts at requests, depending on how this is done, it can occupy an amount of RAM memory and have unnecessary CPU usage, the problem is already was detected that it is the lack of connection, then you must wait for the connection to be re-established to continue with the process. I would answer letter (C), but I hope someone who has more knowledge and experience can answer in a more informed way than I do. I'm just opening the discussion.

Letter (a) and (b) provide a useful offline state as the app can save data, allowing the user to be able to use the app even without a connection and then when the connection is resumed this data will be used to continue the process interrupted by lack of connection.

The letter (d) also provides a useful offline state, many apps have warnings informing that the device is not connected to the internet, so that the user tries to reconnect the device and continue with the process, remembering that these warnings cannot disturb the user or bother you with too many notifications in the status bar and notification drawer. Below are some apps that warn you about the lack of connection.

![letra4](https://user-images.githubusercontent.com/70476123/174345147-d613fbc4-4220-4fc2-b115-f3e147e88d2f.png)

**Comment by masoudk1990** [comment]
> Hello friend, I believe the answer to question 65 is letter **(c) "queuing outbound requests to action when connectivity has been lost"**. I believe that if the device is not connected or has lost the connection, it has no reason to mount a queue or make several attempts at requests, depending on how this is done, it can occupy an amount of RAM memory and have unnecessary CPU usage, the problem is already was detected that it is the lack of connection, then you must wait for the connection to be re-established to continue with the process. I would answer letter (C), but I hope someone who has more knowledge and experience can answer in a more informed way than I do. I'm just opening the discussion.
> 
> Letter (a) and (b) provide a useful offline state as the app can save data, allowing the user to be able to use the app even without a connection and then when the connection is resumed this data will be used to continue the process interrupted by lack of connection.
> 
> The letter (d) also provides a useful offline state, many apps have warnings informing that the device is not connected to the internet, so that the user tries to reconnect the device and continue with the process, remembering that these warnings cannot disturb the user or bother you with too many notifications in the status bar and notification drawer. Below are some apps that warn you about the lack of connection.
> 
> ![letra4](https://user-images.githubusercontent.com/70476123/174345147-d613fbc4-4220-4fc2-b115-f3e147e88d2f.png)

It seems you are pointing to Q65 of something else than OOP :)

**Comment by lucioaguiar** [comment]
You're right, I thought the question was about android, but now that I'm noting that it's about **object-oriented programming**, I'm going to delete the comment and open a new issue as question 65 about **android** is also unanswered. Thanks for the notification.

**Comment by Ebazhanov** [comment]
Thank you @FlorinChess @masoudk1990 @lucioaguiar 👍
