### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by Ebazhanov** [Ebazhanov/linkedin-skill-assessments-quizzes#3940]
![image](https://user-images.githubusercontent.com/13170022/177254391-a8b986a8-2e86-45c7-a6a1-76dd51853775.png)

**Comment by jquiaios** [comment]
The answer is the last one, `DROP TEMPORARY TABLE customers;`

Explanations : Since there are a temporary and a non-temporary tables both called "customers", using the first answer would drop the non-temporary table instead of the temporary one.

Sources : 
https://dev.mysql.com/doc/refman/8.0/en/drop-table.html
https://www.mysqltutorial.org/mysql-temporary-table/

**Comment by Just2Deep** [comment]
This question is already present in the list. 
 Q46

**Comment by Ebazhanov** [comment]
Thank you guys @jquiaios @Just2Deep great job 👍 
i have added both references fyi
