### ISSUE TITLE
New C Question

### ISSUE THREAD

**Issue by Westly** [Ebazhanov/linkedin-skill-assessments-quizzes#4346]
![linkedin_new_C_question](https://user-images.githubusercontent.com/3219403/188339893-f035301d-ea95-450d-bb84-6493e49298f6.png)

**Comment by smashcoder** [comment]
The Correct Answer to this question is
`printf("%s",string[1][2]);`

Explanation : This matrix is not defined in 2D because which this command is not valid and there will no output.

Below are the Images of Correct Codes along with Output

![image](https://user-images.githubusercontent.com/91045061/189171639-5af67250-19cd-40db-a11d-5323ffd3cbd1.png)
![image](https://user-images.githubusercontent.com/91045061/189171946-1ae59792-c923-4a38-a280-4949a074364a.png)
![image](https://user-images.githubusercontent.com/91045061/189172211-5575035d-130a-40f6-a0be-82fc4efbf415.png)

**Comment by MakendranG** [comment]
@Ebazhanov 
I am working on it

**Comment by MakendranG** [comment]
Hi @Ebazhanov

I have worked on this issue and raised a PR https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4699

Kindly merge it.
