### ISSUE TITLE
Answers on the GIT quiz wrong

### ISSUE THREAD

**Issue by huykon** [Ebazhanov/linkedin-skill-assessments-quizzes#5216]
Hey, I was using the answers on the GIT quiz. I didn't have any new questions on there, but the ones I had within the doc are wrong. Not sure How to go about helping up date that.

**Comment by emanuele-em** [comment]
You can send here the Q number or send a PR with answer fix

**Comment by huykon** [comment]
@emanuele-em I'm not sure what questions number but I completed the linkedIn assessment without successful so you guys should re-check the answers please

**Comment by bhollan** [comment]
I just had the same thing.  I followed every answer, but got a 68%.  It seemed like it had all the questions I encountered.

**Comment by emanuele-em** [comment]
@bhollan today I try to fix all the questions

**Comment by gorrinhojr** [comment]
The answers are still wrong :(

**Comment by Ebazhanov** [comment]
> The answers are still wrong :(

please create PR, @gorrinhojr 
thank you in advance

**Comment by Ebazhanov** [comment]
> The answers are still wrong :(

please create PR, @gorrinhojr 
thank you in advance

**Comment by bhollan** [comment]
> Could you elaborate? What do you mean by creating a Pull Request? Thanks for your help

Basically [it's this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request). The main idea is that you'd give suggested answers for the main repo owner to "pull" into their code. The link has all the details, but it's basically fork-original-repo -> edit-your-copy -> make-PR-on-original-repo.  The "edit-your-copy step" in this case would be adding suggested answers to these quiz questions.

I'm swamped this week, otherwise I'd do it. Most of these are googleable (or nowadays ChatGPT-able) questions that are easily found in the docs, but the 90 second time limit makes that nearly impossible during the quiz.
