### ISSUE TITLE
Q6 in the machine learning assessement

### ISSUE THREAD

**Issue by RimelCHERIF** [Ebazhanov/linkedin-skill-assessments-quizzes#5535]
Q6. You want to identify global weather patterns that may have been affected by climate change. To do so, you want to use machine learning algorithms to find patterns that would otherwise be imperceptible to a human meteorologist. What is the place to start?

 I think the right answer is  Create a training set of normal weather and have the machine look for similar patterns. 
In fact, using unsupervised learning to look for anomalies in a massive weather database could be an option, but it may be more difficult to interpret the results without some prior knowledge of what constitutes "normal" weather patterns.

**Comment by monkrus** [comment]
@RimelCHERIF Agreed, training a machine learning algorithm to identify normal patterns can  help to detect patterns that are outside of the norm, potentially indicating the impact of climate change. On the other hand, using unsupervised learning to look for anomalies in a massive weather database could potentially identify unusual weather patterns, but it may not be able to differentiate between patterns caused by climate change and those caused by other factors.

**Comment by monkrus** [comment]
Anser to Q6 has been corrected

**Comment by monkrus** [comment]
@all-contributors please add @RimelCHERIF for code
