### ISSUE TITLE
A lot of the answers for C++ seem to be dubious or wrong

### ISSUE THREAD

**Issue by Property404** [Ebazhanov/linkedin-skill-assessments-quizzes#896]
Q2 - Citation needed. I was under the impression the reason it was bad was that it polluted the global namespace
Q3 - sizeof() only works in bytes, so can you really have a 7-bit struct?
Q5 - iterators are objects, aren't they?
Q10 - Question asks which is NOT a difference
Q13 - The "auto" keyword has been redefined in C++11

I stopped here. Were these the actual solutions to the problems?

**Comment by flomz** [comment]
@Property404 I fixed the erroneous answers you raised in #1109:
- Q2: it is indeed namespace pollution
- Q3: `sizeof()` does work in bytes, but the question here is about [bit fields](https://en.cppreference.com/w/c/language/bit_field), and all the members of the struct do add to 7 bits. However, due to memory alignment, `sizeof(child_t)` will still return 4 bytes which is not one of the available answers...
- Q5: iterators are indeed objects, the answer was wrong
- Q10: the available answers are a bit confusing and I am not sure they were all correctly reported
- Q13: you're right

I fixed some other incorrect answers in the rest of the quizz, hopefully they are all right now.

**Comment by Ebazhanov** [comment]
will be closed based on this https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1215/files
thanks you @rradfar for updating and @Property404 for raising this issue.
